print(range(10))
print(type(range(10)))
print(list("abc"))
print(list(range(10)))
print(tuple("abc"))
print(tuple(range(10)))
print(list(range(3, 9)))
print(len(list(range(3, 9))))
print(len(range(10)))
print(list(range(2, 11, 2)))
